### ISSUE TITLE
Set up web Crawler and begin basic design

### ISSUE THREAD

**Issue by bfbachmann** [ubclaunchpad/sleuth#8]

**Comment by bobheadxi** [comment]
**Edit: just using Scrapy**

# Notes
### Alternatively, could use something like [scrapy](https://scrapy.org/), which does most of the hard work for us as far as setting up a rudimentary crawler goes

## Crawlers
from [quora](https://www.quora.com/How-can-I-build-a-web-crawler-from-scratch-What-language-or-framework-would-you-recommend/answer/Raghavendran-Balu):

> A bare minimum crawler needs at least these components:
> 1. HTTP Fetcher: To retrieve web page from the server.
> 2. Extractor: Minimal support to extract URL from page like anchor links.
> 3. Duplicate Eliminator: To make sure same content is not extracted twice unintentionally. Consider it as a set based data structure.
> 4. URL Frontier: To prioritize URL that has to fetched and parsed. Consider it as a priority queue
> 5. Datastore: To store retrieve pages and URL and other meta data.

### Crawler Work Flow
A spider takes:
- starting URL
- parameters (search terms, max page count)
1. Visit first page, download data, remove url from to-visit
2. Extract links, can do checks on links before adding them to to-visit
3. Visit the next link, repeat

### Revisit Policy
based on
* Age: t-(modification time of page), 0 if unchanged


## Tools
* native library
    * HTMLParser - reading HTML
        * https://docs.python.org/2/library/htmlparser.html
    * urllib, urllib2, urllib.request, urllib.error - opening links
        * https://docs.python.org/2/library/urllib.html
    * multiprocessing, threading - parallelizing spiders
        * https://stackoverflow.com/questions/17241663/filling-a-queue-and-managing-multiprocessing-in-python
        * https://stackoverflow.com/questions/10800593/python-multithreading-crawler
* will probably need to write a specific parsing library
